[package]
name = "mdbook-katex"
version = "0.2.8"
authors = ["Lucas Zanini <zanini.lcs@gmail.com>"]
edition = "2018"
description = "mdBook preprocessor rendering LaTex equations to HTML."
license = "MIT"
readme = "README.md"

[dependencies]
katex = "0.3.2"
clap = "2.33.3"
mdbook = "0.4.4"
serde_json = "1.0.59"
toml = "0.5.7"
